[plugins.drive]
address = http://127.9.9.1:6608
# tags = fs files download upload backup store 
accent = #859f60
root = /drive
depict = store, share and backup your files [not yet available]

[colors.qahwa]
pinned 
[colors.qahwa.props]
red = #A95525 0                     
green = #87a187 1                  
blue = #63310c 2                   
black = black 3                    
white = #f0f8ff 4                  
abstract = #f0f8ff35 5             
opaque = #dccc8ec9 6               
grad-start = rgb(214, 210, 204) 7  
grad-end = rgb(171, 139, 89) 8     
grad-rotate = 328deg 9             
cap = #ffb85e 10                   
ra = #f1fcf6 11                    
[colors.qahwa.selectors]
:root = 0 1 2 3 4 5 6 7 8 9
svg.capra_svg = 10 11
