[package]
name = "capra-ini"
version = "0.1.0"
edition = "2024"

[[example]]
name = "config-file"
path = "examples/config_file.rs"

[[example]]
name = "e1"
path = "examples/test.rs"

[dependencies]
num-into-ascii = { version = "0.1.0", path = "../../../num-into-ascii" }
serde = { version = "1.0.228", features = ["derive"] }
